### ISSUE TITLE
userChrome.css questions, comments, suggestions

### ISSUE THREAD

**Issue by irvinm** [irvinm/Toggle-Native-Tab-Bar#3]
Add anything you might have about userChrome.css related to this addon.

**Comment by Nicolas-GE** [comment]
i added the version 133+ css but it is not working on my end, any help?
i have been using it before and the custom flag to enable css is still enabled

firefox 133, windows 10 22H2

**Comment by Rayquaza01** [comment]
I'm unsure if this works on all platforms, or just Linux, but you can move the window controls from the tab bar to the nav bar with CSS.

I grabbed this trick from Firefox GNOME Theme [here](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/6cbc3b6eceb4195edab67daecc8daa7347c84c27/theme/parts/csd.css#L12), and [here](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/6cbc3b6eceb4195edab67daecc8daa7347c84c27/theme/parts/tabsbar.css#L24)

```css
#main-window[titlepreface*=" "] {
    #TabsToolbar {
        display: none;

        .titlebar-buttonbox-container {
            display: none !important;
        }
    }

    #nav-bar {
        .titlebar-buttonbox-container {
            display: flex !important;
        }
    }
}
```

This will move the window controls to the nav bar when the tab bar is hidden.

Tabs bar visible:
![Screenshot From 2024-12-20 00-37-45](https://github.com/user-attachments/assets/77aeb461-3c9c-4528-b0a7-4fcb5bad0971)

Tab bar hidden, window controls moved:
![Screenshot From 2024-12-20 00-37-52](https://github.com/user-attachments/assets/d3327d17-7f33-4e73-957c-19f47c348b6e)
